AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - app/helpers/*
    - db/schema.rb
    - db/seeds/**/*
    - db/seeds.rb
    - db/custom_seed.rake
    - db/old_migrations/**/*
    - node_modules/**/*
    - bin/**/*
    - app/uploaders/**/*
    - lib/tasks/**/*
    - test/**/*
    - config/environments/*
    - Guardfile
    - Gemfile

Layout/IndentationWidth:
  Width: 2
  Exclude:
    - "db/**/*"

Layout/IndentationStyle:
  Exclude:
    - "db/**/*"

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Naming/AccessorMethodName:
  Exclude:
    - "app/models/user.rb"

Style/AsciiComments:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - "app/models/user.rb"

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: predicate

Style/NumericLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 1000

Metrics/BlockLength:
  Max: 1500

Metrics/BlockNesting:
  Max: 7

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Max: 200

Metrics/MethodLength:
  Max: 1000

Metrics/ModuleLength:
  Max: 1000

Metrics/PerceivedComplexity:
  Max: 200

Lint/UnifiedInteger:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ClassAndModuleChildren:
  SupportedStyles:
    - nested
    - compact

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
