version: '3'
services:
  db_development:
    image: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: iou
      POSTGRES_USER: iou
      POSTGRES_PASSWORD: password

  db_test:
    image: postgres
    ports:
      - "25432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: iou
      POSTGRES_USER: iou
      POSTGRES_PASSWORD: password

