---
swagger: '2.0'
info:
  title: API V1
  version: v1
  description: This is the first version of my API
paths:
  "/users.json":
    post:
      summary: Register a new user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - password
          - password_confirmation
      responses:
        '201':
          description: User created
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              email:
                type: string
